### ISSUE TITLE
Support proxy authentication with dictionary

### ISSUE THREAD

**Issue by seldcat** [jxlil/scrapy-impersonate#13]
Hello!

I hope you're doing well. I have a feature request that I believe would enhance the usability of your project: supporting proxy settings as a dictionary. Currently, when processing a proxy, the parser mistakenly encodes the dictionary, causing the request to the proxy server to fail with [error 5](https://curl.se/libcurl/c/libcurl-errors.html#:~:text=CURLE_COULDNT_RESOLVE_PROXY%20(5),not%20be%20resolved).

**Proposed Solution**
To address this issue, I suggest the following:

**Detection**: When decoding the authentication proxy from the headers, check if the line contains a dictionary.
**Encoding**: If a dictionary is detected, extract these settings and encode them correctly: `urllib.parse.quote(json.dumps(settings, separators=(',', ':')))`
**Replacement**: Replace the dictionary in the decoded string with the encoded settings.

By implementing these steps, the proxy settings should be processed correctly, allowing the request to be sent successfully.

Thank you for considering this enhancement. It would greatly improve the functionality and flexibility of handling proxy settings.

**Comment by jxlil** [comment]
Hi @seldcat, thanks for your comment.

Could you provide an example of how you are making the request, so I can test?

**Comment by seldcat** [comment]
If we consider a typical proxy format:
```
<scheme>://<user>:<pass>@<host>:<port>
```
In my case, the `pass` field is a dictionary with keys like `token`, `country`, etc. When using such proxies, the current implementation fails because it doesn’t encode the dictionary properly.

To resolve this, you need to encode the dictionary as I describer earlier.

**Comment by seldcat** [comment]
It's worth noting that Scrapy decodes the username and password when collecting the header (see [this line in the Scrapy source code](https://github.com/scrapy/scrapy/blob/master/scrapy/downloadermiddlewares/httpproxy.py#L45)). However, `scrapy-impersonate` does not encode it back. Therefore, if the username or password contains special characters, it will cause a crash.

Also, everything works fine for me if I disable the `scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware` (the password and login are decoded here and then not properly encoded, sending the improperly encoded password to the next stage), so perhaps the problem is on my side.

**Comment by jxlil** [comment]
Sorry, I've been a little busy, I'm going to get back to this today.

**Comment by jxlil** [comment]
Now, `RequestParser` does not handle proxy authentication, so you can use custom authentication instead:

```python
yield Request(
    url=f"http://example.com",
    headers={
        "Proxy-Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyX2lkIiwiZXhwIjowMDAwMDAwMDAwfQ.8ZLkrPvu9-hKLnq8fghbZYdv-a-KMJfHtSndfFmT3PQ",
    },
    meta={
        "impersonate": "chrome110",
        "proxy": "http://0.0.0.0:80000",
    },
)
```
