### ISSUE TITLE
Support of fresh browser versions

### ISSUE THREAD

**Issue by VicZagranowski** [jxlil/scrapy-impersonate#5]
Hello, please let us know if you have plans to release support new brosers versions chrome 120+ in you future updates?

**Comment by jxlil** [comment]
Hi, scrapy-impersonate depends on the [curl_cffi](https://github.com/yifeikong/curl_cffi) project. At the moment there do not seem to be plans to add support for those versions: https://github.com/users/yifeikong/projects/1

**Comment by jxlil** [comment]
Hi @VicZagranowski

In version [1.3.0](https://github.com/jxlil/scrapy-impersonate/releases/tag/1.3.0) there are two new Chrome browsers available:

-`chrome123` (123.0.6312.124)
-`chrome124` (124.0.6367.60)

**Comment by jxlil** [comment]
I made a mistake, these two versions will be available until version 0.7.0 of [curl_cffi](https://pypi.org/project/curl-cffi/) is released.

**Comment by jxlil** [comment]
Yes, today I will update this. Thanks!

**Comment by jxlil** [comment]
In version `1.3.1` there are two new Chrome browsers available:

- `chrome123` (123.0.6312.124)
- `chrome124` (124.0.6367.60)
